### ISSUE TITLE
Children in the suffix tree

### ISSUE THREAD

**Issue by lucasmoschen** [lucasresck/Search-engine#6]
What do you think about the following idea? 

When we add a new suffix, we compare with all the alphabet letters, linear time. I thought, so, if we could build a BST with the values we added, so, when we compare, we do with a balanced BST, log n time. We reduce of 128 to 7, it's a big improve! 

I can try to implement this in a new branch,  if you like.

**Comment by lucasresck** [comment]
When we add a new suffix, we do not compare with all the alphabet letter. We just look at the first letter and convert it to ASCII value. I think it's done in constant time.
